### ISSUE TITLE
Pagination is off by one

### ISSUE THREAD

**Issue by millette** [local-npm/local-npm#111]
For example, searching for "pump" on http://localhost:5080/_browse/#/
shows exactly 10 results, yet the "Next" button is still available and leads to a page with 0 results.

P.S.: I should be able to find the time to fix this (and the markdown bug).

**Comment by nolanlawson** [comment]
Sorry, yeah! That looks like a UI bug.

**Comment by gabrielcsapo** [comment]
@millette are you interested in still fixing this bug?

**Comment by gabrielcsapo** [comment]
This issue seems to longer exist, please reopen if you see otherwise.
