### ISSUE TITLE
request entity too large

### ISSUE THREAD

**Issue by gajus** [local-npm/local-npm#113]
Getting en error "request entity too large" when trying to publish a package that uses [`bundledDependencies`](https://docs.npmjs.com/files/package.json#bundleddependencies).

```
npm ERR! registry error parsing json
npm ERR! publish Failed PUT 413
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/gajus/.nvm/versions/node/v5.10.0/bin/node" "/Users/gajus/.nvm/versions/node/v5.10.0/bin/npm" "publish"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3

npm ERR! Unexpected token E
npm ERR! Error: request entity too large<br> &nbsp; &nbsp;at makeError (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/raw-body/index.js:198:15)<br> &nbsp; &nbsp;at module.exports (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/raw-body/index.js:40:15)<br> &nbsp; &nbsp;at handleProxy (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express-http-proxy/index.js:66:5)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at next (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/route.js:131:13)<br> &nbsp; &nbsp;at Route.dispatch (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/route.js:112:3)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at /Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/index.js:277:22<br> &nbsp; &nbsp;at param (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/index.js:349:14)<br> &nbsp; &nbsp;at param (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/index.js:365:14)<br> &nbsp; &nbsp;at Function.process_params (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/index.js:410:3)<br> &nbsp; &nbsp;at next (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/index.js:271:10)<br> &nbsp; &nbsp;at favicon (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/serve-favicon/index.js:72:7)<br> &nbsp; &nbsp;at Layer.handle [as handle_request] (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/layer.js:95:5)<br> &nbsp; &nbsp;at trim_prefix (/Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/index.js:312:13)<br> &nbsp; &nbsp;at /Users/gajus/.nvm/versions/node/v5.10.0/lib/node_modules/local-npm/node_modules/express/lib/router/index.js:280:7
npm ERR!
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/gajus/Documents/dev/canonical-code-style/canonical/npm-debug.log
[fsevents] Success: "/Users/gajus/Documents/dev/canonical-code-style/canonical/node_modules/fsevents/lib/binding/Release/node-v47-darwin-x64/fse.node" is installed via remote
canonical@3.1.9 /Users/gajus/Documents/dev/canonical-code-style/canonical
```

**Comment by nolanlawson** [comment]
I can actually reproduce this issue and have run into it several times before. I'm guessing it's because I need to up the limit in the Express settings for the `PUT` request.

As a temporary hacky workaround, typically you can add a `"files"` member to your `package.json` and limit the number of files you're uploading to npm. I've found that usually fixes it, and it's also kind of a good habit.

**Comment by gajus** [comment]
> As a temporary hacky workaround, typically you can add a "files" member to your package.json and limit the number of files you're uploading to npm. I've found that usually fixes it, and it's also kind of a good habit.

This is missing entirely the point of [`bundledDependencies`](https://docs.npmjs.com/files/package.json#bundleddependencies) property(, which is to upload all files, including those in `./node_modules` to NPM).

**Comment by nolanlawson** [comment]
Ah gotcha, that's probably what's pushing it over the limit.

**Comment by gajus** [comment]
Now, to make myself more useful:

1. I can see that `local-npm` is [using `express-http-proxy`](https://github.com/nolanlawson/local-npm/blob/eddacf9070acd1fc08e681ea379f72eed13948b6/package.json#L31).
1. `express-http-proxy` is [using `raw-body`](https://github.com/villadora/express-http-proxy/blob/02527df12bcb328932c90fa71aedcc0a398e556c/index.js#L7).
1. `express-http-proxy` [initialises `raw-body`](https://github.com/villadora/express-http-proxy/blob/02527df12bcb328932c90fa71aedcc0a398e556c/index.js#L66) using [`options` parameter](https://github.com/villadora/express-http-proxy/blob/02527df12bcb328932c90fa71aedcc0a398e556c/index.js#L11).
1. `options` parameter defines [`limit` property](https://github.com/villadora/express-http-proxy/blob/02527df12bcb328932c90fa71aedcc0a398e556c/index.js#L47) that corresponds to [`raw-body` `limit` property](https://github.com/stream-utils/raw-body#getrawbodystream-options-callback).
1. [`local-npm` initialises `express-http-proxy`](https://github.com/nolanlawson/local-npm/blob/eddacf9070acd1fc08e681ea379f72eed13948b6/lib/index.js#L248) without setting the `options` parameter.
1. `options.limit` property [defaults to 1m](https://github.com/villadora/express-http-proxy/blob/02527df12bcb328932c90fa71aedcc0a398e556c/index.js#L47).

There is no good reason enforce any limit on a local proxy. To fix the issue, please [initialise `express-http-proxy`](https://github.com/nolanlawson/local-npm/blob/eddacf9070acd1fc08e681ea379f72eed13948b6/lib/index.js#L248) using `{limit: Infinity}` setting, e.g.

```js
app.put('/*', proxy(FAT_REMOTE, {
    limit: Infinity
}));
```

**Comment by gajus** [comment]
Looking at the implementation of `raw-body`, it [attempts to convert `limit` to a finite number](https://github.com/stream-utils/raw-body/blob/f4ec2a5f6e9573c1ed126111b831c246b6ca580e/index.js#L97) using [`bytes.parse`](https://www.npmjs.com/package/bytes#bytesparsestring-value-numbernull). With that in mind, setting limit to `1gb` should cover all foreseeable use cases.

**Comment by nolanlawson** [comment]
Cool! I'm fine with a super high limit like that.

**Comment by gajus** [comment]
> Cool! I'm fine with a super high limit like that. Open a PR? 😃

No, please continue on your own. PRs only make sense for sensible pieces of code. This is just adding a config.

**Comment by gabrielcsapo** [comment]
@gajus I updated the config as per your prescribed fix here https://github.com/local-npm/local-npm/pull/135 can you look over and see if this works for your use case also?
