### ISSUE TITLE
Can't serve private npm modules

### ISSUE THREAD

**Issue by byronhulcher** [local-npm/local-npm#116]
I had trouble installing private javascript modules hosted on https://registry.npmjs.org/  When I would attempt to install one I would get:

```
bhulcher$ npm install -g <@org name>/<package name>
npm ERR! Darwin 15.3.0
npm ERR! argv "/Users/bhulcher/.nvm/versions/node/v5.10.0/bin/node" "/Users/bhulcher/.nvm/versions/node/v5.10.0/bin/npm" "install" "-g" "<@org name>/<package name>"
npm ERR! node v5.10.0
npm ERR! npm  v3.8.3
npm ERR! code E404

npm ERR! 404 Not found : <@org name>/<package name>
npm ERR! 404 
npm ERR! 404  '<@org name>/<package name>' is not in the npm registry.
npm ERR! 404 You should bug the author to publish it (or use the name yourself!)
npm ERR! 404 
npm ERR! 404 Note that you can also install from a
npm ERR! 404 tarball, folder, http url, or git url.

npm ERR! Please include the following file with any support request:
npm ERR!     /Users/bhulcher/src/<package name>/npm-debug.log
```

Note: Yes, I did replace my package name with `<@org name>/<package name>` but I assure you I did entire a real package that exists on npmjs.com

Switching to the default registry using `npm set registry https://registry.npmjs.org/` allowed me to install the package.  

Let me know if I can help out with any more detail!

**Comment by tyler-johnson** [comment]
I had the same issue, here's a solution: https://github.com/nolanlawson/local-npm/issues/108#issuecomment-195521353

**Comment by nolanlawson** [comment]
Hm, I don't have much experience with private modules, but I'm guessing the fix is that we need to pass the credentials from the original HTTP request on to `npmjs.org`, so that it serves a 200 instead of a 404. Sorry that I don't have a ton of time to work on this right now, but any pull requests would be welcome, and you'll probably want to start [here](https://github.com/nolanlawson/local-npm/blob/eddacf9070acd1fc08e681ea379f72eed13948b6/lib/index.js#L139-L184).

**Comment by byronhulcher** [comment]
Thanks for the reference @tyler-johnson, I neglected to check the closed issues.  A good stop-gap.

@nolanlawson Thanks for the pointer in the right direction!  I'll keep this in my back pocket for the next boroughgramming.

**Comment by gabrielcsapo** [comment]
scoped packages should work, let me know if you are still having issues.
