### ISSUE TITLE
Add support for "downloads" metadata.

### ISSUE THREAD

**Issue by mralexgray** [local-npm/local-npm#120]
Download **counts**, _that is_.

_Personally_, I wouldn't mind if the data was infrequently updated, stale even.

There's plenty of ways to do it.. 

Am happy to put in my 2 cents if the concept is amenable.

**Comment by nolanlawson** [comment]
I believe this is covered by https://github.com/nolanlawson/local-npm/issues/46, so closing as a dup, but please let me know if I misdiagnosed.

**Comment by mralexgray** [comment]
@nolanlawson I'm not quite sure how #46 manifests itself, day-to-day..  but it doesn't seem related to this issue, at all, as far as i can tell..  no?

**Comment by nolanlawson** [comment]
#46 contains the "view" logic, which is what npm uses to generate these counts (I believe).

**Comment by gabrielcsapo** [comment]
@mralexgray would you like to discuss this issue further. I feel like it would be a good feature add to the project.
