### ISSUE TITLE
[enhancement]shasum error. Because is not compatible with cnpmjs.

### ISSUE THREAD

**Issue by wusisu** [local-npm/local-npm#123]
## problem

It occurs "shasum check failed" error.
the whole sentence is 

```
npm ERR! shasum check failed for /var/folders/cc/n1t9n30s45509jsbws5v723h0000gn/T/npm-61661-e421db3b/192.168.174.233_5080/tarballs/koa-static/1.5.2.tgz
```

and the `cat ....koa-static/1.5.2.tgz` is

```
{"error":"not_found","reason":"document not found"}%
```
## why

This error comes by setting a [cnpmjs](https://github.com/cnpm/cnpmjs.org) repository as a "--remote" fullfatdb. 
It may be because of the different strategy of the url for downloading.
## fix

I think this is a lack function more than a bug.
And have no idea because have not look into the code.
But a fix for this will greatly helpful. (https://registry.npmjs.org here is slow)

**Comment by gabrielcsapo** [comment]
@wusisu does this issue still persist?

**Comment by wusisu** [comment]
I think that may be my wrong expectation about how to use local-npm with --remote and --remote-skim.

A fast npm registry mirror here in China is https://registry.npm.taobao.org/ , which is built by [cnpmjs](https://cnpmjs.org/).
And It provide no skim-db, so I try to run local-npm by 
```
local-npm --url-base http://192.168.0.48:5080 --remote https://registry.npm.taobao.org/
```

I run `npm install 1grids` with this registry and it return errors:
```
npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/Cellar/node/7.4.0/bin/node" "/usr/local/bin/npm" "install" "1grids"
npm ERR! node v7.4.0
npm ERR! npm  v4.0.5

npm ERR! shasum check failed for /var/folders/bl/749wcppx5c1724jwyd00t8xh0000gq/T/npm-25864-825d51d8/192.168.0.48_5080/tarballs/1grids/4.0.6.tgz
npm ERR! Expected: d01bb78a00d88fcc1f9100042b98dd2671111abe
npm ERR! Actual:   8d065612f683d9f8df207e665ab24398309c912e
npm ERR! From:     http://192.168.0.48:5080/tarballs/1grids/4.0.6.tgz
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     /private/tmp/aaaa/npm-debug.log
```

while 
```
>curl http://192.168.0.48:5080/tarballs/1grids/4.0.6.tgz
{"error":"not_found","reason":"document not found"}%
```

---------------------

I try `npm show 1grids` using https://registry.npm.taobao.org/, and I get tarball:
```
dist:
   { shasum: 'd01bb78a00d88fcc1f9100042b98dd2671111abe',
     size: 4639,
     noattachment: false,
     tarball: 'http://registry.npm.taobao.org/1grids/download/1grids-4.0.6.tgz' }
```
other than using https://registry.npmjs.org
```
dist:
   { shasum: 'd01bb78a00d88fcc1f9100042b98dd2671111abe',
     tarball: 'https://registry.npmjs.org/1grids/-/1grids-4.0.6.tgz' }
```

I think this could be a reason why comes error.

----------------------------------

This is not so boring me, because using registry.npmjs.org seems acceptable.

**Comment by wusisu** [comment]
When I `curl http://192.168.0.48:5080/tarballs/1grids/4.0.6.tgz`
console on local-npm prints as follows:
```
hashes don't match, not returning
not cached 1grids at version 4.0.6, downloading...
GET /tarballs/1grids/4.0.6.tgz 200 109.462 ms - 51
downloaded 1grids at version 4.0.6 and saved it locally
```

---------------

Thanks for help.

**Comment by gabrielcsapo** [comment]
@wusisu okay this seems like a valid bug because the tar never gets downloaded because the forwarded url is `https://registry.npm.taobao.org/tarballs/1grids/4.0.6.tgz` which returns `{"error":"not_found","reason":"document not found"}` looking at a possible solve for this.

**Comment by gabrielcsapo** [comment]
@wusisu okay the issue was here (https://github.com/local-npm/local-npm/blob/master/lib/index.js#L109) because it makes assumptions of where the tarball should be here (https://github.com/local-npm/local-npm/blob/master/lib/index.js#L222).

So I made a change that if it reaches line 222 meaning that it needs to go get the tar from the source repository it will go and fetch the info so now it looks like this;

> npm

```
Gabriels-MacBook-Pro-2:temp gabrielcsapo$ npm get registry
http://127.0.0.1:5080/
Gabriels-MacBook-Pro-2:temp gabrielcsapo$ npm install 1grids
temp@1.0.0 /Users/gabrielcsapo/Desktop/temp
└── 1grids@4.0.6 

npm WARN temp@1.0.0 No description
npm WARN temp@1.0.0 No repository field.
```

The server side defers to the info route in the case of not knowing the tarbal location

```
{ shasum: 'd01bb78a00d88fcc1f9100042b98dd2671111abe',
  tarball: 'http://127.0.0.1:5080/tarballs/1grids/4.0.6.tgz',
  info: 'http://127.0.0.1:5080/1grids/4.0.6' }
``` 

working on formalizing it and opening up a PR. Looks like it might be a fix that you were looking for! 😄

**Comment by gabrielcsapo** [comment]
The real issue here is that we assume the location of the tarball when the location can change depending on the registry.

**Comment by gabrielcsapo** [comment]
@wusisu would you be able to pull down the changes in https://github.com/local-npm/local-npm/pull/139 and see if it fixes the issue you were seeing?

**Comment by wusisu** [comment]
It works for me now.

The situation is much more simple than I thought. 233333
Thanks a lot.

**Comment by gabrielcsapo** [comment]
@wusisu I will publish a patch version tomorrow, thanks for your help!
