### ISSUE TITLE
project direction

### ISSUE THREAD

**Issue by gabrielcsapo** [local-npm/local-npm#134]
let's use this as a forum for what the community thinks the direction of this module should be.

**Comment by gabrielcsapo** [comment]
I think the first thing that has to be done is groom the issues and see what is a valid feature add or if it is stale and already completed.

**Comment by gabrielcsapo** [comment]
@whmilton what do you think?

**Comment by wmhilton** [comment]
@gbarielcsapo I think you're doing a great job!

**Comment by gabrielcsapo** [comment]
@wmhilton you rock man! 😄
