### ISSUE TITLE
move to react? 

### ISSUE THREAD

**Issue by gabrielcsapo** [local-npm/local-npm#137]
thoughts on moving the project to react or something similar to simplify the front-end code base?

**Comment by wmhilton** [comment]
I vote for either React or Vue. I *really* struggled to understand enough how to edit the front-end to make some minor changes. (And not just this project - any Angular project I've tried to hack on. And I've even spent a few hours trying to familiarize myself with Angular.)

**Comment by gabrielcsapo** [comment]
I really like react, it has been super helpful on a ton of projects. Do you have any ideas for UI tweak @wmhilton? I think we should mirror a lot of what npmjs.org looks like, they seem to have gotten what is useful information down to a science!

**Comment by wmhilton** [comment]
Oh, I don't think a slavish copying of npmjs.org is necessary. Honestly, a lot of the information they put at the very bottom (dependencies & dependents) is what I find most useful. And... well here lemme just put on my super critical hat.

![image](https://cloud.githubusercontent.com/assets/587740/26335696/b05eea52-3f3b-11e7-9449-de00fe085414.png)

First go at "improving" it by emphasizing the bits I find important and de-emphasizing the bits I find noise:

![image](https://cloud.githubusercontent.com/assets/587740/26336497/d9aa1a12-3f40-11e7-8e48-4d8ed9c79c2d.png)

It's no masterpiece. But look at Yarn for instance:

![image](https://cloud.githubusercontent.com/assets/587740/26336515/eb79a8d4-3f40-11e7-9873-a831a6a02f30.png)

There is not a ton of imagination in this space. Now, that out of the way, local-npm / modserv is clearly the worst offender.

![image](https://cloud.githubusercontent.com/assets/587740/26336537/1be3e9d0-3f41-11e7-810a-a779c311b3b6.png)

So honestly, you can't do any damage. I mean, maybe if you made the whole thing a bulleted list, that would be worse. But yeah, React, and if you want to make it stand apart from the crowd, maybe a Material Design look? Hmm... https://github.com/callemall/material-ui looks really cool. I'd be down to learn that!

As long as it's still a snappy single page app, it doesn't matter to me if you just tweak it or do a full rewrite. Just work smart. :)

**Comment by wmhilton** [comment]
Hey, so the [Yarn website](https://github.com/yarnpkg/website)'s website is actually open source. It looks like a pretty straightforward application of React, Bootstrap, and jQuery.

**Comment by wmhilton** [comment]
I spoke too soon. It's got that, but also ruby on rails or jekyll or something. `npm start` just compiled some files, no visible sign of the webpage itself.

**Comment by gabrielcsapo** [comment]
@wmhilton really awesome work showing what information is valuable. 

I like the yarn site, simple and elegant. I'm not a big material UI fan, but I have been working on this http://www.gabrielcsapo.com/psychic-ui/ and use it in a bunch of projects. It has the same properties of being simple like the yarn site. 

I like the use of all of the screen real-estate as seen below;

<img width="1346" alt="screen shot 2017-05-22 at 11 32 23 pm" src="https://cloud.githubusercontent.com/assets/1854811/26341130/ed791d58-3f46-11e7-911a-ad516d586ebd.png">

I agree a quick single page application would be key in this addition. @wmhilton what do you think about this?
