### ISSUE TITLE
Issue with scoped packages

### ISSUE THREAD

**Issue by burjua** [local-npm/local-npm#146]
Seems like the package is maintained again, but the issue with scoped packages still exists. 

Obvious culprits are @angular or @ng-bootstrap, e.g. I'm getting this error while trying to install a package: 

```
C:\Program Files\Far Manager>npm set registry http://web-dev-08-zz:5080/

>npm install
npm ERR! code ECONNRESET
npm ERR! errno ECONNRESET
npm ERR! network request to http://web-dev-08-zz:5080/@ng-bootstrap%2fng-bootstrap failed, reason: socket hang up
npm ERR! network This is a problem related to network connectivity.
npm ERR! network In most cases you are behind a proxy or have bad network settings.
npm ERR! network
npm ERR! network If you are behind a proxy, please make sure that the
npm ERR! network 'proxy' config is set properly.  See: 'npm help config'

npm ERR! A complete log of this run can be found in:
npm ERR!  
```

**Comment by gabrielcsapo** [comment]
@burjua so the problem exists when requesting `http://web-dev-08-zz:5080/@ng-bootstrap%2fng-bootstrap` what does this respond when you do a normal get via your browser or curl?

**Comment by gabrielcsapo** [comment]
@burjua I added a fix here https://github.com/local-npm/local-npm/pull/147, would you mind taking a look and seeing if this fixes the problem you were seeing?

**Comment by burjua** [comment]
@gabrielcsapo thanks for adding the fix. It's not published to the npm repository though, is it? How do I install and test it?

**Comment by gabrielcsapo** [comment]
I added a comment to the PR.

**Comment by gabrielcsapo** [comment]
@burjua

**Comment by burjua** [comment]
Hi @gabrielcsapo , thanks for your help, my setup is a bit complicated and I don't know npm configuration that well so it's hard to test and verify it's working.
I installed local-npm globally, started it and run "npm set registry http://127.0.0.1:5080"

However I have this in my C:\Users\\[username]\\.npmrc:
```
registry=http://127.0.0.1:5080
@angular:registry=http://registry.npmjs.org/
@ng-bootstrap:registry=http://registry.npmjs.org/
@telerik:registry=http://registry.npmjs.org/
@types:registry=http://registry.npmjs.org/
```

Am I right to assume that only non-scoped packages will be cached by local-npm and scoped ones will be downloaded from the npm registry directly? 
How can I know for sure if the package was cached/loaded from cache or downloaded from npm?
With this setup "npm-install" worked on the machine 1 where local-npm is running.

Hovewer if I update C:\Users\\[username]\\.npmrc to 

```
registry=http://127.0.0.1:5080
@angular:registry=http://127.0.0.1:5080
@ng-bootstrap:registry=http://127.0.0.1:5080
@telerik:registry=http://127.0.0.1:5080
@types:registry=http:http://127.0.0.1:5080
```
And run "npm install" it doesn't work, I get 
```
npm ERR! Cannot read property 'replace' of null
npm ERR! Cannot read property 'replace' of null
npm ERR! Cannot read property 'replace' of null
```
But honestly, I don't know what I'm doing in this case. 

It would be nice to update documentation on npm site to include examples how to work with scoped packages. Also would be good to add some info on how to work with pacakges from different repos, especially if they require authentications, e.g. like @progress: http://www.telerik.com/kendo-angular-ui/getting-started/#toc-add-the-progress-npm-registry 

Also my idea was to use a tool like "local-npm" to have local npm repository that can be used from different machine within networks, build agents etc. I couldn't make it work so far though. 

Cheers

**Comment by gabrielcsapo** [comment]
You will know that the package is cached when you do an `npm install` and it will not proxy to the public registry. 

The update stores both scoped and non-scoped packages. 

When you say;

```
Also my idea was to use a tool like "local-npm" to have local npm repository that can be used from different machines within the network, build agents etc. I couldn't make it work so far though.
```

Do you want use `npm-local` as a multi tenant system? This seems very simple, you can access it from anywhere in the network 😄

**Comment by gabrielcsapo** [comment]
@burjua I have merged can you try reinstalling and seeing if the scoped-modules problem exists?

**Comment by StormToft** [comment]
@gabrielcsapo 

I'm using release 2.2.1 and I'm having issues with scoped packages. This is my first time using local-npm. Here's example npm install output:

```
http fetch GET 200 http://myhost.com:5080/istanbul 118ms
http fetch GET 200 http://myhost.com:5080/handlebars 114ms
http fetch GET 200 http://myhost.com:5080/tarballs/istanbul/0.4.5.tgz 63ms
http fetch GET 200 http://myhost.com:5080/yargs 59ms
http fetch GET 200 http://myhost.com:5080/tarballs/yargs/3.10.0.tgz 18ms
http fetch GET 200 http://myhost.com:5080/tarballs/yargs/8.0.2.tgz 25ms
http fetch GET 200 http://myhost.com:5080/cross-spawn 131ms
http fetch GET 200 http://myhost.com:5080/tarballs/cross-spawn/3.0.1.tgz 22ms
http fetch GET 200 http://myhost.com:5080/tarballs/handlebars/4.0.10.tgz 361ms
http fetch GET 500 http://myhost.com:5080/@types%2fhammerjs 70788ms attempt #3
http fetch GET 500 http://myhost.com:5080/@types%2fwebpack 70842ms attempt #3
http fetch GET 500 http://myhost.com:5080/@types%2fjasmine 70898ms attempt #3
http fetch GET 500 http://myhost.com:5080/@compodoc%2fcompodoc 71706ms attempt #3
http fetch GET 500 http://myhost.com:5080/@angularclass%2fhmr-loader 71633ms attempt #3
http fetch GET 500 http://myhost.com:5080/@angularclass%2fhmr 71631ms attempt #3
http fetch GET 500 http://myhost.com:5080/@angular%2fplatform-browser 71785ms attempt #3
```

Notice the scoped packages all failing. Any other info you need that would be helpful?

**Comment by gabrielcsapo** [comment]
interesting how it looks like something is stalling when downloading from the source since the time is the maximum threshold `local-npm` has to download the package `~70000ms`. Would you be able to post this as another issue @StormToft so I can update the status and add tests accordingly.
