### ISSUE TITLE
install failed on both Ubuntu & Win10

### ISSUE THREAD

**Issue by Elitward** [local-npm/local-npm#158]
[2017-08-10T08_56_41_015Z-debug.zip](https://github.com/local-npm/local-npm/files/1214486/2017-08-10T08_56_41_015Z-debug.zip)
Try to install local-npm on new machines, both Ubuntu & Win10 Pro, both failed. Looks like same reason.

Win 10:
node -v = 8.2.1
npm -v = 5.3.0

Error message from CMD terminal:

C:\>**npm install -g windows-build-tools**

> windows-build-tools@1.3.2 postinstall C:\Users\YeHua.Deng\AppData\Roaming\npm\node_modules\windows-build-tools
> node ./lib/index.js

Downloading BuildTools_Full.exe
Downloading python-2.7.13.msi
[>                                            ] 0.0% (0 B/s)
Downloaded python-2.7.13.msi. Saved to C:\Users\YeHua.Deng\.windows-build-tools\python-2.7.13.msi.
Starting installation...
Launched installers, now waiting for them to finish.
This will likely take some time - please be patient!
_Waiting for installers... \Successfully installed Python 2.7
Successfully installed Visual Studio Build Tools._
+ windows-build-tools@1.3.2
added 128 packages in 51.603s

C:\>**npm install -g local-npm**
C:\Users\YeHua.Deng\AppData\Roaming\npm\local-npm -> C:\Users\YeHua.Deng\AppData\Roaming\npm\node_modules\local-npm\bin\index.js

> leveldown@1.7.2 install C:\Users\YeHua.Deng\AppData\Roaming\npm\node_modules\local-npm\node_modules\leveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.2
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v1.7.2-node-v57-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\YeHua.Deng\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v57-win32-x64.tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\YeHua.Deng\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\YeHua.Deng\AppData\Roaming\npm\node_modules\local-npm\node_modules\leveldown\build\Release\leveldown.node
prebuild-install info unpack required C:\Users\YeHua.Deng\AppData\Roaming\npm\node_modules\local-npm\node_modules\leveldown\build\Release\leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> leveldown@1.5.0 install C:\Users\YeHua.Deng\AppData\Roaming\npm\node_modules\local-npm\node_modules\pouchdb\node_modules\leveldown
> prebuild --install

prebuild info begin Prebuild version 4.5.0
prebuild info looking for local prebuild @ prebuilds\leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild info looking for cached prebuild @ C:\Users\YeHua.Deng\AppData\Roaming\npm-cache\_prebuilds\https-github.com-level-leveldown-releases-download-v1.5.0-leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild http request GET https://github.com/level/leveldown/releases/download/v1.5.0/leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild http 404 https://github.com/level/leveldown/releases/download/v1.5.0/leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild WARN install No prebuilt binaries found (target=v8.2.1 arch=x64 platform=win32)
prebuild info install We will now try to compile from source.
prebuild verb starting node-gyp process
prebuild verb execute node-gyp with `node index.js rebuild --target=v8.2.1 --target_arch=x64`
prebuild verb ok
prebuild verb ok
prebuild verb ok
Building the projects in this solution one at a time. To enable parallel build, please add the "/m" switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\YeHua.
Deng\AppData\Roaming\npm\node_modules\local-npm\node_modules\pouchdb\node_modules\leveldown\deps\leveldb\leveldb.vcxpro
j]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.targets(36,5): error
 MSB8036: The Windows SDK version 8.1 was not found. Install the required version of Windows SDK or change the SDK vers
ion in the project property pages or by right-clicking the solution and selecting "Retarget solution". [C:\Users\YeHua.
Deng\AppData\Roaming\npm\node_modules\local-npm\node_modules\pouchdb\node_modules\leveldown\deps\snappy\snappy.vcxproj]
prebuild ERR! build error
prebuild ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! stack     at ChildProcess.onExit (C:\Users\YeHua.Deng\AppData\Roaming\npm\node_modules\local-npm\node_modules\node-gyp\lib\build.js:258:23)
prebuild ERR! stack     at emitTwo (events.js:125:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:213:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok
prebuild ERR! build Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit code: 1
prebuild ERR! build     at ChildProcess.onExit (C:\Users\YeHua.Deng\AppData\Roaming\npm\node_modules\local-npm\node_modules\node-gyp\lib\build.js:258:23)
prebuild ERR! build     at emitTwo (events.js:125:13)
prebuild ERR! build     at ChildProcess.emit (events.js:213:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\YeHua.Deng\AppData\Roaming\npm-cache\_logs\2017-08-10T08_56_41_015Z-debug.log

C:\>

**Comment by Elitward** [comment]
Ubuntu Error Message:


[linux-terminal-error.zip](https://github.com/local-npm/local-npm/files/1214494/linux-terminal-error.zip)

**Comment by wmhilton** [comment]
I don't know if this will fix it, but here is some information that might help!

The Ubuntu install failed because you tried to install a package globally without sudo permissions:

```
elitward@upweulnx01:~$ npm install -g local-npm
npm WARN checkPermissions Missing write access to /usr/local/lib
/usr/local/lib
└─┬ local-npm@2.2.0 
  ├── colors@1.1.2 
...
18345 verbose stack Error: EACCES: permission denied, access '/usr/local/lib'
...
18355 error Error: EACCES: permission denied, access '/usr/local/lib'
...
18356 error Please try running this command again as root/Administrator.
18357 verbose exit [ -13, true ]
```

The next attempt failed because `node` wasn't available in the PATH. Probably easily resolved by logging out and logging back in again.
```
elitward@upweulnx01:~$ sudo npm install -g local-npm
/usr/local/bin/local-npm -> /usr/local/lib/node_modules/local-npm/bin/index.js

> leveldown@1.5.0 install /usr/local/lib/node_modules/local-npm/node_modules/pouchdb/node_modules/leveldown
> prebuild --install

/usr/bin/env: ‘node’: No such file or directory
/usr/local/lib
└── (empty)
```

Frankly I have always had a *terrible* time installing Node with Ubuntu's built in package management system. It is always out of date (did you notice it was installing Node 4.x and npm 3.x?) or does weird things like separate "node" and "npm" into separate packages. I almost always opt to just download the Linux binaries (either the 32-bit or 64-bit depending on your OS) directly from the nodejs website: https://nodejs.org/en/download/current/

Here's an install script from of my projects. It was for version 4.x and npm 3.x but I've updated the version numbers for you, hopefully it will still work. Since it's an install script it is meant to be run with sudo.
```sh
#!/usr/bin/env bash
set -e
set +x
# wget is only used to download the installer.
# xz-utils is used by tar to extract Nodejs
apt update && apt install wget xz-utils -y && apt clean
# Install Nodejs
cd /opt
wget https://nodejs.org/dist/v8.3.0/node-v8.3.0-linux-x64.tar.xz
tar xf node-*.tar.xz
rm node-*.tar.xz
mv node-* node
# Modify PATH
source /etc/environment
echo "PATH=\"/opt/node/bin:$PATH\"" >> /etc/environment
source /etc/environment
# Update npm
npm install --global npm@latest
npm list -g
```

**Comment by gmastergreatee** [comment]
node -v = 8.2.1
npm -v = 5.3.0

Failed for Windows 8 too :- 

```
E:\ngProjects>npm install -g local-npm
C:\Users\GMaster\AppData\Roaming\npm\local-npm -> C:\Users\GMaster\AppData\Roaming\npm\node_modules\
local-npm\bin\index.js

> leveldown@1.7.2 install C:\Users\GMaster\AppData\Roaming\npm\node_modules\local-npm\node_modules\l
eveldown
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.2.2
prebuild-install info looking for local prebuild @ prebuilds\leveldown-v1.7.2-node-v57-win32-x64.tar
.gz
prebuild-install info looking for cached prebuild @ C:\Users\GMaster\AppData\Roaming\npm-cache\_preb
uilds\https-github.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v57-win32-x64.
tar.gz
prebuild-install info found cached prebuild
prebuild-install info unpacking @ C:\Users\GMaster\AppData\Roaming\npm-cache\_prebuilds\https-github
.com-level-leveldown-releases-download-v1.7.2-leveldown-v1.7.2-node-v57-win32-x64.tar.gz
prebuild-install info unpack resolved to C:\Users\GMaster\AppData\Roaming\npm\node_modules\local-npm
\node_modules\leveldown\build\Release\leveldown.node
prebuild-install info unpack required C:\Users\GMaster\AppData\Roaming\npm\node_modules\local-npm\no
de_modules\leveldown\build\Release\leveldown.node successfully
prebuild-install info install Successfully installed prebuilt binary!

> leveldown@1.5.0 install C:\Users\GMaster\AppData\Roaming\npm\node_modules\local-npm\node_modules\p
ouchdb\node_modules\leveldown
> prebuild --install

prebuild info begin Prebuild version 4.5.0
prebuild info looking for local prebuild @ prebuilds\leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild info looking for cached prebuild @ C:\Users\GMaster\AppData\Roaming\npm-cache\_prebuilds\ht
tps-github.com-level-leveldown-releases-download-v1.5.0-leveldown-v1.5.0-node-v57-win32-x64.tar.gz
prebuild http request GET https://github.com/level/leveldown/releases/download/v1.5.0/leveldown-v1.5
.0-node-v57-win32-x64.tar.gz
prebuild http 404 https://github.com/level/leveldown/releases/download/v1.5.0/leveldown-v1.5.0-node-
v57-win32-x64.tar.gz
prebuild WARN install No prebuilt binaries found (target=v8.2.1 arch=x64 platform=win32)
prebuild info install We will now try to compile from source.
prebuild verb starting node-gyp process
prebuild verb execute node-gyp with `node index.js rebuild --target=v8.2.1 --target_arch=x64`
prebuild verb ok
prebuild verb ok
prebuild verb ok
Building the projects in this solution one at a time. To enable parallel build, please add the "/m"
switch.
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.
targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required versi
on of Windows SDK or change the SDK version in the project property pages or by right-clicking the
solution and selecting "Retarget solution". [C:\Users\GMaster\AppData\Roaming\npm\node_modules\loca
l-npm\node_modules\pouchdb\node_modules\leveldown\deps\leveldb\leveldb.vcxproj]
C:\Program Files (x86)\MSBuild\Microsoft.Cpp\v4.0\V140\Platforms\x64\PlatformToolsets\v140\Toolset.
targets(36,5): error MSB8036: The Windows SDK version 8.1 was not found. Install the required versi
on of Windows SDK or change the SDK version in the project property pages or by right-clicking the
solution and selecting "Retarget solution". [C:\Users\GMaster\AppData\Roaming\npm\node_modules\loca
l-npm\node_modules\pouchdb\node_modules\leveldown\deps\snappy\snappy.vcxproj]
prebuild ERR! build error
prebuild ERR! stack Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit co
de: 1
prebuild ERR! stack     at ChildProcess.onExit (C:\Users\GMaster\AppData\Roaming\npm\node_modules\lo
cal-npm\node_modules\node-gyp\lib\build.js:258:23)
prebuild ERR! stack     at emitTwo (events.js:125:13)
prebuild ERR! stack     at ChildProcess.emit (events.js:213:7)
prebuild ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
prebuild ERR! not ok
prebuild ERR! build Error: `C:\Program Files (x86)\MSBuild\14.0\bin\msbuild.exe` failed with exit co
de: 1
prebuild ERR! build     at ChildProcess.onExit (C:\Users\GMaster\AppData\Roaming\npm\node_modules\lo
cal-npm\node_modules\node-gyp\lib\build.js:258:23)
prebuild ERR! build     at emitTwo (events.js:125:13)
prebuild ERR! build     at ChildProcess.emit (events.js:213:7)
prebuild ERR! build     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)
npm ERR! code ELIFECYCLE
npm ERR! errno 2
npm ERR! leveldown@1.5.0 install: `prebuild --install`
npm ERR! Exit status 2
npm ERR!
npm ERR! Failed at the leveldown@1.5.0 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\GMaster\AppData\Roaming\npm-cache\_logs\2017-08-12T06_13_25_388Z-debug.log
```

**Comment by gabrielcsapo** [comment]
It seems like a problem with leveldown, does it occur for earlier versions of leveldown? @elitward @gmastergreatee

**Comment by Elitward** [comment]
I have the same feeling. leveldown is the reason.

**Comment by gabrielcsapo** [comment]
@Elitward @gmastergreatee @wmhilton might be a good time to move something like https://github.com/zkat/cacache, instead of a c++ cache, this could do the trick!

**Comment by gmastergreatee** [comment]
@gabrielcsapo There are no problems installing the latest version(1.7.2) of leveldown. The problem exists because the current package tries to install an older version(1.5.0).

**Comment by gmastergreatee** [comment]
Possible fixes may include updating the __"pouchdb"__ version in the __"package.json"__ file. The current version included(6.2.0) has a dependency on leveldown(1.5.0<-- root of the problem) whereas the latest version of __"pouchdb"__(6.2.1-prerelease) has updated dependency of leveldown(1.7.2).

**Comment by gabrielcsapo** [comment]
@gmastergreatee I am going to hold off for a "fix" until pouchdb is released into their stable release cycle. @nolanlawson do you have a timetable for that main release? `6.2.1`

**Comment by gabrielcsapo** [comment]
Looks like this got merged, going to update this tomorrow

**Comment by gabrielcsapo** [comment]
fixed in https://github.com/local-npm/local-npm/releases/tag/2.2.2 sorry for the late change!
