### ISSUE TITLE
Tip: For those in China

### ISSUE THREAD

**Issue by pacav69** [local-npm/local-npm#47]
# For those that are in China to use the Chinese registry

first install npmrc
    npm install npmrc -g
    npmrc
     npmrc -r cn

The first line installs the app
then initialize it to setup default
npmrc -r [registry]   to use an npm mirror  - in this case the china mirror
## Alternative

use 
http://npm.taobao.org to get npm packages
to setup
     npmrc -c taobao

To use:
npmrc default
and to switch to china server
npmrc taobao
# local-npm

If you want to use a local-npm repositry then use the remote option

Remote registry at china server
local-npm -R http://registry.npm.taobao.org/
## help section from npmrc

 Switch between different .npmrc files with ease and grace.

usage:
 npmrc                 list all profiles
 npmrc [name]          change npmrc profile (uses fuzzy matching)
 npmrc -c [name]       create a new npmrc profile called name
 npmrc -r [registry]   to use an npm mirror

available mirrors for npmrc -r:
 au      - Australian registry mirror
 eu      - European registry mirror
 cn      - Chinese registry mirror
 default - Default registry

example:

 # Creating and activating a new .npmrc called "work":

 $ npmrc -c work

 # Switch betwen "work" and "default"

 $ npmrc work
 $ npmrc default
 # Use the European npm mirror  $ npmrc -r eu

**Comment by nolanlawson** [comment]
Good to know! Do you think this would make sense as part of the README?

**Comment by pacav69** [comment]
I gave it to you to add to your readme if you wanted to.

I think it makes sense to add it as you have mentioned the austrlian one.

On Wed, Aug 26, 2015 at 9:05 PM, Nolan Lawson <notifications@github.com>
wrote:

> Good to know! Do you think this would make sense as part of the README?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/nolanlawson/local-npm/issues/47#issuecomment-135004181>
> .
>



-- 
Paul Cavanagh
Business and IT Consultant
+86-13774291848
------------------------------------------------
http://silverpcgroup.com/
Webhosting and Web Development

Dropbox for Android, iPhone and file sharing
http://db.tt/664PP2JA

For those with smartphones you can scan the QR Code
Paul Cav QR Code
<https://docs.google.com/drawings/d/1gaMyNmCjS1MeiTd8qhX2BU46txJG7N7gDrNCKgJorC0/edit>

**Comment by pacav69** [comment]
i updated the original post to make it more clearer

**Comment by gabrielcsapo** [comment]
@pacav69 is this still a valid tip?

**Comment by pacav69** [comment]
@gabrielcsapo  i believe so, i'm not in china any more so i'm unable to confirm.
'
