### ISSUE TITLE
Slow loading times, 1 - 3 seconds per package

### ISSUE THREAD

**Issue by OmgImAlexis** [local-npm/local-npm#53]
As you can see I'm getting between 1 and 3 seconds for some of my packages even though I had just run `npm install`.
Shouldn't this be faster since it's already downloaded those packages the first time I ran `npm install`?

```
local-npm-0 GET /os-name 304 17.730 ms - -
local-npm-0 GET /object-assign 200 21.770 ms - -
local-npm-0 GET /chalk 304 1152.665 ms - -
local-npm-0 GET /configstore 304 1621.630 ms - -
local-npm-0 GET /inquirer 304 2061.907 ms - -
local-npm-0 GET /xdg-basedir 304 6.666 ms - -
local-npm-0 GET /user-home 304 770.410 ms - -
local-npm-0 GET /uuid 304 1101.557 ms - -
local-npm-0 GET /graceful-fs 304 1361.589 ms - -
local-npm-0 GET /js-yaml 304 1941.291 ms - -
local-npm-0 GET /esprima 304 1963.567 ms - -
local-npm-0 GET /argparse 304 2221.692 ms - -
local-npm-0 GET /inherit 304 2244.285 ms - -
local-npm-0 GET /sprintf-js 304 1918.798 ms - -
local-npm-0 GET /lodash 304 7534.282 ms - -
local-npm-0 GET /lodash.isfunction 304 5.733 ms - -
local-npm-0 GET /lodash.isobject 304 10.476 ms - -
local-npm-0 GET /lodash.now 304 13.117 ms - -
local-npm-0 GET /lodash._objecttypes 304 2.931 ms - -
local-npm-0 GET /lodash._isnative 304 1.427 ms - -
local-npm-0 GET /win-release 304 3.705 ms - -
local-npm-0 GET /osx-release 304 5.265 ms - -
local-npm-0 GET /minimist 304 1084.798 ms - -
local-npm-0 GET /semver 304 1959.615 ms - -
```

**Comment by nolanlawson** [comment]
Yeah, I've been using it as my personal npm server for awhile now, and I've noticed that sometimes it's pretty slow as well. Needs investigation.

**Comment by nolanlawson** [comment]
Well, I just tried comparing `local-npm` to regular npm, for installing all dependencies of a large project (PouchDB), on a slow café wifi in Brooklyn. Results:

* local-npm: 4m37.412s
* regular npm: 14m52.772s

Steps to repro:

```
hub clone --single-branch --depth 1 -b master pouchdb/pouchdb
cd pouchdb
time npm install
```

So I guess npm is just crazy slow these days. I'm using npm 3.3.5 and node 4.0.0 BTW.

**Comment by OmgImAlexis** [comment]
I'm guessing it's something to do with the way npm 3 works. :disappointed:

**Comment by nolanlawson** [comment]
I ran some tests. Looks like `local-npm` is slower for the first install, but faster afterwards: https://github.com/nolanlawson/test-local-npm-speed#readme

**Comment by OmgImAlexis** [comment]
Does it cache both the metadata and the full tarball for each npm module? Just trying to think of ways to speed it up.
Having my cache on a local SSD should get me sub 1 minute install times on my repos but I still end up with a full `npm install` taking around 5 minutes.

**Comment by nolanlawson** [comment]
It really depends on your repo. Many packages have postinstall steps that take a long time (e.g. compiling from C, downloading a tarball from somewhere other than npm, etc.).

And yes, after the first time, both the metadata and tarballs are cached. So if it's taking a long time even after the second install, then that's purely non-network npm stuff. (Turn off your Internet and retry to verify.)

**Comment by elgubenis** [comment]
hey, i compared install speeds of npm@2 vs npm@3 both using the local-npm registry, just felt an urge to post it somewhere:

npm@2 took 1m 3s
npm@3 took 3m 14s

not sure if its important but the replication was not yet at 100% when the comparison was done, jfyi.

**Comment by elgubenis** [comment]
```js
dependencies: {
    "body-parser": "^1.14.2",
    "compression": "^1.6.0",
    "connect-redis": "^3.0.2",
    "cookie-parser": "^1.4.1",
    "corser": "^2.0.0",
    "debug": "^2.2.0",
    "express": "^4.13.3",
    "express-session": "^1.13.0",
    "fs-walk": "0.0.1",
    "js-yaml": "^3.5.2",
    "mongoose": "^4.3.6",
    "response-time": "^2.3.1",
    "socket.io": "^1.4.4",
    "socket.io-redis": "^1.0.0",
    "underscore": "^1.8.3"
}
```

**Comment by nolanlawson** [comment]
Interesting. :) I do know that npm3 adds extra time because of the module deduping.

**Comment by gabrielcsapo** [comment]
@omgimalexis do you have recent thoughts on this issue?

**Comment by OmgImAlexis** [comment]
I use yarn now so I don't really have any use for this. I went through and closed 100+ issues I had opened. I just reopened this as I noticed you had added tags only a few days ago.

**Comment by gabrielcsapo** [comment]
@OmgImAlexis yarn still uses npm registries right?

**Comment by OmgImAlexis** [comment]
Yes it does but it also heavily caches stuff. I'm not sure if two caches is really going to be of any benefit.

**Comment by gabrielcsapo** [comment]
@OmgImAlexis thanks for the info! I think I will close this issue, unless other people using this are experiencing this problem. Right now I am getting speeds sub 50 ms from the cache.
